### PR TITLE
Fix Homewizard alternate positive/negative current bug

### LINKED ISSUE #213: homewizzard current from negative to positive and back.
**Describe the bug**
using the new homeassistant P1 meter integration the Amps switch between negative and positive values. 
This while it should all be negative 

**Upload your config**
`{"version":"v3.8.1","serialnr":7879,"mode":"SOLAR","mode_id":2,"car_connected":true,"wifi":{"status":"WL_CONNECTED","ssid":"XXXXX","rssi":-68,"bssid":"XXXXXX"},"evse":{"temp":26,"temp_max":65,"connected":true,"access":1,"mode":2,"loadbl":0,"pwm":248,"custombutton":false,"solar_stop_timer":0,"state":"Charging","state_id":2,"error":"None","error_id":0,"rfid":"Not Installed"},"settings":{"charge_current":146,"override_current":0,"current_min":6,"current_max":20,"current_main":25,"current_max_circuit":20,"current_max_sum_mains":0,"max_sum_mains_time":0,"solar_max_import":10,"solar_start_current":10,"solar_stop_time":10,"enable_C2":"Not present","mains_meter":"HmWzrd P1","starttime":0,"stoptime":0,"repeat":0,"lcdlock":0},"mqtt":{"host":"192.168.1.85","port":1883,"topic_prefix":"SmartEVSE/7879","username":"","password_set":false,"status":"Connected"},"ocpp":{"mode":"Disabled","backend_url":"","cb_id":"","auth_key":"","auto_auth":"Disabled","auto_auth_idtag":"","status":"Disconnected"},"home_battery":{"current":0,"last_update":0},"ev_meter":{"description":"Eastron3P","address":103,"import_active_power":8.600000381,"total_kwh":9203.099609,"charged_kwh":2.799999952,"currents":{"TOTAL":384,"L1":131,"L2":127,"L3":126},"import_active_energy":9203.099609,"export_active_energy":0},"mains_meter":{"import_active_energy":0,"export_active_energy":0,"host":"p1meter-11DB82.local"},"phase_currents":{"TOTAL":-52,"L1":-17,"L2":-15,"L3":-20,"last_data_update":1746617818,"original_data":{"TOTAL":-52,"L1":-17,"L2":-15,"L3":-20}},"backlight":{"timer":120,"status":"ON"},"color":{"off":{"R":0,"G":0,"B":0},"normal":{"R":0,"G":255,"B":0},"smart":{"R":0,"G":255,"B":0},"solar":{"R":255,"G":170,"B":0},"custom":{"R":0,"G":0,"B":255}}}
`

**Upload a debug log**
Don't have this yet

**To Reproduce**
1. What Mode are you in? Normal, Smart or Solar?
       Solar
3. What steps do you take so the problem arises?
even without charging a car the P1 meter will change the value from negative to positive and back without any real logic.
This means the charge current will go up and down very rapidly.
see the screenshots of the weird behaviour

**Screenshots**

Image

Image

Image

### PR DESCRIPTION
**Pull request by kozmoz**
…. This fixes #213

### CODE REVIEW

File: SmartEVSE-3/src/network.cpp [hunk 1]
```diff
@@ -865,16 +865,18 @@ std::pair<int8_t, std::array<std::int8_t, 3> > getMainsFromHomeWizardP1() {
...
     // Process all three phases.
-    std::array<int8_t, 3> currents;
+    std::array<int16_t, 3> currents{};
     for (size_t i = 0; i < phases; ++i) {
-        int rawCurrent = doc[currentKeys[i]].as<float>() * 10;
-        currents[i] = std::abs(rawCurrent) * getCorrection(powerKeys[i]);
+        const auto rawCurrentFloat = doc[currentKeys[i]].as<float>();
+        const auto currentInDeciAmps = static_cast<int16_t>(std::round(rawCurrentFloat * 10));
+        const auto absCurrentInDeciAmps = std::abs(currentInDeciAmps);
+        currents[i] = static_cast<int16_t>(absCurrentInDeciAmps * getCorrection(powerKeys[i]));
```
Comment (dingo35) [inline SmartEVSE-3/src/network.cpp:879]: I don't like this part of the code:
-it doesnt make sense to me to declare a variable auto and then cast <int16_t> to it
-most of the currents in SmartEVSE code are in dA; this was a choice made by the manufacturer at start, and I still consider it an excellent choice: we have 1 decimal precision without having to deal with floats. So putting "DeciAmps" in the variable name might suggest to other coders that variables without that in the name are using Amps. So better leave "DeciAmps" out of the name and add comment if you want to stress it is in dA.
-I don't like the multiplication of the number of lines
-I like atomic changes, that is changes that are as little change as possible to show what problem they are actually solving.

Wouldnt it be simpler, instead of this whole block 876-879, to just change 876 to:
int16_t rawCurrent = doc[currentKeys[i]].as<float>() * 10;      ?

**Review by dingo35 — CHANGES_REQUESTED** [review]

File: SmartEVSE-3/src/network.cpp (hunk 1 above)
Comment (kozmoz) [reply SmartEVSE-3/src/network.cpp]: **I reverted the changes to the most atomic form possible.**

Only during the review I realized that deciAmps were being used which was not initially clear to me. Hence the descriptive variable names.

To eliminate the warnings in the code I added explicit type casting after every calculation. This change made the line very long so I refactored them into simplified and descriptive steps for clarity.

I think the root cause of the bug was traced back to inconsistent type casts and ignored warnings. The current code is functioning correctly, but there are still quit some warnings in my editor. 

* Uninitialized record type: 'currents' 
* Narrowing conversion from 'typename enable_if<!ConverterNeedsWriteableRef<float>::value, float>::type' (aka 'float') to 'int' 
* Narrowing conversion from 'int' to signed type 'std::array<short, 3>::value_type' (aka 'short') is implementation-defined 
* Local variable 'rawCurrent' can be made const

Comment (dingo35) [reply SmartEVSE-3/src/network.cpp]: My compiler gives 0 warnings; your IDE editor is tuned too cautiously to my taste:
-currents IS initialized immediately after its declaration
-yes the conversion is narrowing because that is exactly what we aim to do: go from float to int
-not sure what line this is on, but I think int RawCurrent should be int16_t RawCurrent; AFAIK int is by default int16_t in Arduino, but why take the risk?
-IMHO those const labels are only cluttering our code; the compiler will determine something is a const and will optimize it; usually the binary is exactly the same, whether you declare it const or not.

I will change that one line and commit the PR, THANKS for your work!!!

Comment (kozmoz) [reply SmartEVSE-3/src/network.cpp]: I'm not quite sure why my editor (CLion) prefers explicit initialization, casts, and constants. It does seem to clutter the code indeed. As I mentioned before, I don’t have much experience with embedded systems or C/C++. My background is primarily in JavaScript, TypeScript, and Java, where IntelliJ's warnings are always helpful suggestions.

Comment (dingo35) [reply SmartEVSE-3/src/network.cpp]: I still prefer good old vi and gcc :-)

Comment (dingo35) [reply SmartEVSE-3/src/network.cpp]: So if your background is in javascript, we are more C / C++ guys; so if you have any suggestions on improving our javascript/html code, Im open to suggestions !
